services:
  valley:
    build:
      context: docker
      dockerfile: Dockerfile-steam
      args:
        ## Recommended: set as env_variable during build
        STEAM_USER: ${STEAM_USER}
        ## Recommended: set as env_variable during build
        STEAM_PASS: ${STEAM_PASS}
        ## Recommended: set as env_variable during build
        STEAM_GUARD: ${STEAM_GUARD}
        ## Stardew steamId
        SRCDS_APPID: 413150
    container_name: stardew
    environment:
      # VNC
      VNC_PASSWORD: whocares
      DISPLAY_HEIGHT: 900
      DISPLAY_WIDTH: 1200
      X11VNC_EXTRA_OPTS: "-noxdamage -reopen -forever"
  
      # Always On Server mod
      ENABLE_ALWAYSONSERVER_MOD: true

      # Auto Load Game mod
      ENABLE_AUTOLOADGAME_MOD: true
      AUTO_LOAD_GAME_LAST_FILE_LOADED: null
      AUTO_LOAD_GAME_FORGET_LAST_FILE_ON_TITLE: true
      AUTO_LOAD_GAME_LOAD_INTO_MULTIPLAYER: true

      # Unlimited Players Mod
      ENABLE_UNLIMITEDPLAYERS_MOD: true
      UNLIMITED_PLAYERS_PLAYER_LIMIT: 10

      # Chat Commands mod
      ENABLE_CHATCOMMANDS_MOD: true

    ports:
      # VNC, disable port, use web (is better)
      # - 5902:5900
      # NOVNC WEB
      - "5801:5800"
      # Game  
      - "24642:24642/udp"
    volumes:
      # Saves go here now
      - ./valley_saves:/config/xdg/config/StardewValley/Saves
      # If you'd like to set an existing savegame before the first start otherwise this file will be edited when starting the first game
      - ./configs/autoload.json:/data/Stardew/game/Mods/AutoLoadGame/config.json
